[pyprland]
plugins = [
  "layout_center",
  "scratchpads"
]

[layout_center]
margin = 50
offset = [0, 0]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"
style = ["opacity 1", "bordercolor rgb(FFFF00)"]
captive_focus = false

[scratchpads.filemanager]
animation = ""
command = "nemo"
class = "nemo"
lazy = false
size = "60% 60%"
margin = 0
skip_windowrules = ["aspect", "workspace"]

[scratchpads.musicplayer]
animation = ""
command = "spotify"
class = "Spotify"
lazy = true
size = "70% 70%"
margin = 0
