name: NixOS

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - 'GNOME.md'
      - 'README.md'
      - 'notes/**'
      - '.git-crypt/**'
      - '.gitattributes'
      - '.gitignore'

jobs:
  home-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Get pinned nixpkgs ‚ùÑÔ∏è"
        id: pinned_nixpkgs
        run: echo "::set-output name=url::$(cat ./pinned/nixpkgs)"

      - name: "Install Nix ‚ùÑÔ∏è"
        uses: cachix/install-nix-action@v13
        with:
          nix_path: "nixpkgs=${{ steps.pinned_nixpkgs.outputs.url }}"

      - name: "Install Cachix ‚ùÑÔ∏è"
        uses: cachix/cachix-action@v10
        with:
          name: gvolpe-nixos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # Needed because cachix is also installed by Home Manager
      - name: "Set priority flag for Cachix üö©"
        run: nix-env --set-flag priority 0 cachix

      - name: "Build Home Manager config üè†"
        run: ./build.sh ci

  system-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Get pinned nixpkgs ‚ùÑÔ∏è"
        id: pinned_nixpkgs
        run: echo "::set-output name=url::$(cat ./pinned/nixpkgs)"

      - name: "Get NixOS configuration file ‚ùÑÔ∏è"
        id: nixos_configuration
        run: echo "::set-output name=filename::$(pwd)/system/configuration.nix"

      - name: "Install Nix ‚ùÑÔ∏è"
        uses: cachix/install-nix-action@v13
        with:
          nix_path: "nixpkgs=${{ steps.pinned_nixpkgs.outputs.url }}"

      - name: "Install Cachix ‚ùÑÔ∏è"
        uses: cachix/cachix-action@v10
        with:
          name: gvolpe-nixos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build NixOS config ‚ùÑÔ∏è"
        run: nix-build '<nixpkgs/nixos>' -I nixos-config=${{ steps.nixos_configuration.outputs.filename }} -A system
